name: Python application

on:
  schedule:
    - cron:  '00 23-3 * * 1' #イギリス時間で毎日23時（日本は8時）に実行してほしい。が、1～2時間くらい遅れる計算

  push:
    branches: [main]

  workflow_dispatch:
    branches: [main]

jobs:
  getAPI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        cd getAPI
        python main.py #メインスクリプトを実行

    - name: Commit files
      run: |
        # git config core.filemode false
        # if git diff --exit-code --quiet #差分がある場合だけコミット（上手く動かないので一旦保留）
        # then
          git config --local user.name "twoooooda"
          git config --local user.email "yuuyatsuda0602@gmail.com"
          git add .
          git commit -m "Add fortune data"
          git push
        # fi
      
