name: Python application

on: push

jobs:
  getAPI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}

  # functionに差分があるかチェック
    - name: Check Diff Functions
      id: diff_functions
      uses: technote-space/get-diff-action@v5


    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        cd getAPI
        python main.py #メインスクリプトを実行

    - name: Commit files
      if: steps.diff_functions.outputs.diff
      run: |
        git config core.filemode false
        if ! git diff --exit-code --quiet
        then
          git config --local user.name "twoooooda"
          git config --local user.email "yuyatsuda06022@gmail.com"
          git add .
          git commit -m "Add fortune data"
          git push
        fi
      