name: Python application

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python main.py #メインスクリプトを実行

    - name: Commit files 
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add json_fortune.json
        git commit -m "Add fortune data"
      

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        publish_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
